// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteBook.Data;

namespace NoteBook.Migrations
{
    [DbContext(typeof(NoteBookContext))]
    [Migration("20220415232011_first migration")]
    partial class firstmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoteBook.Models.Journal", b =>
                {
                    b.Property<int>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BackgroundColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Notebook")
                        .HasColumnType("int");

                    b.Property<int>("NotebookId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mood")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("weather")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JournalId");

                    b.HasIndex("Notebook");

                    b.HasIndex("mood");

                    b.HasIndex("weather");

                    b.ToTable("Journal");
                });

            modelBuilder.Entity("NoteBook.Models.Mood", b =>
                {
                    b.Property<string>("MoodPic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MoodId")
                        .HasColumnType("int");

                    b.HasKey("MoodPic");

                    b.ToTable("Mood");
                });

            modelBuilder.Entity("NoteBook.Models.Notebook", b =>
                {
                    b.Property<int>("NotebookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotebookId");

                    b.ToTable("Notebook");
                });

            modelBuilder.Entity("NoteBook.Models.PhotoDiary", b =>
                {
                    b.Property<int>("PhotoDiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Template")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secondContent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhotoDiaryId");

                    b.HasIndex("Template");

                    b.ToTable("PhotoDiary");
                });

            modelBuilder.Entity("NoteBook.Models.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("TemplateId");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("NoteBook.Models.Weather", b =>
                {
                    b.Property<string>("WeatherPic")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WeatherId")
                        .HasColumnType("int");

                    b.HasKey("WeatherPic");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("NoteBook.Models.Journal", b =>
                {
                    b.HasOne("NoteBook.Models.Notebook", "notebook")
                        .WithMany("Journals")
                        .HasForeignKey("Notebook");

                    b.HasOne("NoteBook.Models.Mood", "PrimaryMood")
                        .WithMany("Journals")
                        .HasForeignKey("mood");

                    b.HasOne("NoteBook.Models.Weather", "PrimaryWeather")
                        .WithMany("Journals")
                        .HasForeignKey("weather");

                    b.Navigation("notebook");

                    b.Navigation("PrimaryMood");

                    b.Navigation("PrimaryWeather");
                });

            modelBuilder.Entity("NoteBook.Models.PhotoDiary", b =>
                {
                    b.HasOne("NoteBook.Models.Template", "template")
                        .WithMany()
                        .HasForeignKey("Template");

                    b.Navigation("template");
                });

            modelBuilder.Entity("NoteBook.Models.Mood", b =>
                {
                    b.Navigation("Journals");
                });

            modelBuilder.Entity("NoteBook.Models.Notebook", b =>
                {
                    b.Navigation("Journals");
                });

            modelBuilder.Entity("NoteBook.Models.Weather", b =>
                {
                    b.Navigation("Journals");
                });
#pragma warning restore 612, 618
        }
    }
}
